diagnoses_path = 'data/processed/diagnoses.parquet'

[model]
hidden_size = 256
num_layers  = 3
num_heads   = 4
head_dim    = 32
pos_base    = 10_000
dropout     = 0.5
device      = 'cuda'
mlp_intermediate_size = 1024

[trainer]
hole_prob         = 0.05
masked_loss_gamma = 100
batch_size        = 32
num_epochs        = 1000
learning_rate     = 1e-4
max_patient_len   = 150
eval_split        = 0.15
test_split        = 0.15
weight_decay      = 0.05
eval_batch_size   = 64
ccs_as_inputs     = false
patience          = 50
save_directory    = 'results/filler-%(id)-%(date)/'
# limit_num_batches = 3

[metrics]
recalls = [5, 10, 20, 30]



