diagnoses_path = 'data/processed/diagnoses.parquet'

[model]
pos_base = 10_000
dropout  = 0.7
device   = 'cuda'

[trainer]
batch_size      = 64
num_epochs      = 5
max_patient_len = 150
eval_split      = 0.15
test_split      = 0.15
weight_decay    = 0.05
eval_batch_size = 64
ccs_as_inputs   = false
patience        = 10
save_directory  = 'results/search_kelso_run-%(id)-%(date)/'
search_path     = 'results/search_kelso-%(id)-%(date).csv'
# limit_num_batches = 3

[hyper_search]
hidden_size   = [64, 128, 256]
num_layers    = [2, 5, 10]
num_heads     = [2, 4, 8]
head_dim      = [16, 32, 64]
learning_rate = [1e-3, 1e-4]
mlp_intermediate_size = [512, 1024, 2048]

[metrics]
recalls = [5, 10, 20, 30]



