diagnoses_path = 'data/processed/diagnoses.parquet'
ccs_codes_path = 'data/processed/codes.parquet'

[model]
code_hidden_size        = 64
code_num_layers         = 4
code_num_heads          = 4
code_head_dim           = 32
code_intermediate_size  = 256
visit_hidden_size       = 512
visit_num_layers        = 4
visit_num_heads         = 8
visit_head_dim          = 128
visit_intermediate_size = 2048
dropout_prob            = 0.2
pos_base                = 10_000.0
device                  = 'cuda'

[train]
batch_size      = 64
num_epochs      = 1000
learning_rate   = 1e-4
eval_split      = 0.2
test_split      = 0.2
weight_decay    = 1e-3
eval_batch_size = 256

[metrics]
recalls = [5, 10, 20, 30]
